apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: nginx-ingress
    namespace: prod
  spec:
    ingressClassName: nginx
    rules:
    - host: nginx.ribas.ca
      http:
        paths:
        - backend:
            service:
              name: nginx-svc
              port:
                name: http
          path: /
          pathType: Prefix
